### ISSUE TITLE
Support for Travis CI

### ISSUE THREAD

**Issue by MindTooth** [roosta/vim-srcery#16]
Hi,

Got the idea for this after I saw [this](https://github.com/ryanoasis/vim-devicons/pull/236/).  This uses the `vint` package to lint (no pun intended).

Testing it [here](https://travis-ci.com/MindTooth/vim-srcery) on my own fork. [![Build Status](https://travis-ci.com/MindTooth/vim-srcery.svg?branch=travis)](https://travis-ci.com/MindTooth/vim-srcery)

.travis.yml
```yml
# vim-srcery .travis.yml

language: python

install:
  - pip install vim-vint

script:
  - vint --verbose --stat $(find . -type f -name '*.vim')
```
